version: "2"
services:
  app:
    image: app
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      MYSQL_ROOT_PASSWORD: root
    tty: true
    stdin_open: true
    networks: 
      - my_network

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks: 
      - my_network

networks: 
  my_network:
    driver : bridge
   
