version: "3.3"
services:
  app:
    image: biancatazlauanu/cinema-app:latest-app
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      MYSQL_ROOT_PASSWORD: root
    tty: true
    stdin_open: true

  service:
    image: biancatazlauanu/cinema-app:latest-service
    links:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "5002:5002"
    tty: true
    stdin_open: true
  
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  client:
    image: biancatazlauanu/cinema-app:latest-client
    depends_on:
      - service
    ports:
      - "5001:5001"
    tty: true
    stdin_open: true

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - db
    ports:
      - "3000:3000"
    user: '0'
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
    db_data: {}
    grafana_data: {}
